USE ROLE ACCOUNTADMIN;

-- 1. Create the Custom Role and Service User
CREATE ROLE INFRA_ROLE;
CREATE USER TERRAFORM_USER PASSWORD = '<REDACTED>';
GRANT ROLE INFRA_ROLE TO USER TERRAFORM_USER;

-- 2. Grant SYSADMIN-level infrastructure privileges
GRANT CREATE DATABASE ON ACCOUNT TO ROLE INFRA_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE INFRA_ROLE;

-- 3. Grant SECURITYADMIN-level user/grant privileges
GRANT CREATE USER ON ACCOUNT TO ROLE INFRA_ROLE;
GRANT CREATE ROLE ON ACCOUNT TO ROLE INFRA_ROLE;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE INFRA_ROLE;

-- 4. Ensure SYSADMIN can see what Terraform builds
GRANT ROLE INFRA_ROLE TO ROLE SYSADMIN;

